spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_test
    username: postgres
    password: 1596psql
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  token:
    secret:
      expiry-mills: 600000
      key: SnZUTgGz6u+8PL2auyKJEScKO4XxfPLIvd0WIHrdpLItlVWFQgwWeyzWcgpKMamLWQLF7IsgAPgBqT0Z1otp8Q==